<?php
include_once "../include/commonfunctions.php";
session_start();
openDatabaseConnection();

if(($_GET['type'] == "msword" || $_GET['type'] == "msexcel") && isset($_SESSION['formvalues']) && count($_SESSION['formvalues']) != 0){
$downloadtime = date("d-m-y-Hi")."Hrs";

// required for IE, otherwise Content-disposition is ignored
if(ini_get('zlib.output_compression'))
	ini_set('zlib.output_compression', 'Off');

if($_GET['type'] == "msword"){
	$filename = "SmartGuardDownload-".$downloadtime.".doc";
	# This line will stream the file to the user rather than spray it across the screen
	header("Content-type: application/vnd.ms-word");

} else if($_GET['type'] == "msexcel"){
	$filename = "SmartGuardDownload-".$downloadtime.".xls";
	header("Content-type: application/vnd.ms-excel");

}

# replace excelfile.xls with whatever you want the filename to default to
header("Content-Disposition: attachment;filename=".$filename);
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
$formvalues = $_SESSION['formvalues'];
?>
<table width="100%" border="0" cellpadding="5" cellspacing="2">
  <tr>
    <td colspan="5"><?php echo $_SESSION['reporttype'];?> Report for <b><?php 
	if(isset($_SESSION['shiftdate']) && $_SESSION['shiftdate'] != "0000-00-00 00:00:00"){ echo date("d-M-Y",strtotime($_SESSION['shiftdate']));} else {
		echo date("d-M-Y");
	}?></b> &nbsp;|&nbsp; &nbsp;&nbsp; Generated By <b><?php echo $_SESSION['names'];?></b></td>
  </tr>
  <tr>
    <td colspan="5">
	<table width="100%" border="0" cellspacing="0" cellpadding="2" style="border: 1px; 
	border-style: solid;
	border-color: #adaefe">
      <?php   $query = "";
	  		  $wherestr = "";
//**********************************************************************************************			// If the report is for daily schedule of the guards
//********************************************************************************************** 
			  if($_SESSION['reporttype'] == "Guard Daily Schedule"){
			  	$wherestr = "AND (";
			  	$result = mysql_query("SELECT id, startdate, enddate, exception FROM assignments");
				$exception_in = array();
				// Record all those assignments that are not active today
				while($row = mysql_fetch_array($result,MYSQL_ASSOC)){
					$startdate = date("d-m-Y",strtotime($row['startdate']));
					$enddate = date("d-m-Y",strtotime($row['enddate']));
					$today = date("d-m-Y",strtotime("now"));
					$exception_array = split(",",$row['exception']);
					// If today lies on one of the exception dates
					for($j=0;$j<count($exception_array);$j++){
						if($today == date("d-m-Y",strtotime($exception_array[$j]))){
							array_push($exception_in,$row['id']);
						}
					}
					// If today is out of range of the assignment days
					if($today < $startdate && $today > $enddate){
						array_push($exception_in,$row['id']);
					}
				}
				// remove duplicates
				$exception_in = array_unique($exception_in);
				// generate a where string if the exception array is not empty
				if(count($exception_in) > 0){
					for($k=0;$k<count($exception_in);$k++){
						if($k == 0){
							$wherestr .= " a.id <> '".$exception_in[$k]."'";
						} else {
							$wherestr .= " AND a.id <> '".$exception_in[$k]."'";
						}
					}
					// Close bracket so that these conditions are all considered once in the AND
					$wherestr .= ")";
				}
			  
			  	$query = "SELECT a.callsign, a.client, a.assignedguard, a.startdate, a.enddate, a.exception, a.servicetype, c.name, c.contphone, c.email, c.plotno, c.boxno, c.genphone FROM assignments a, clients c WHERE a.client = c.name ".$wherestr;
			  }
			  
//**********************************************************************************************			// If the report is for item location
//********************************************************************************************** 
			  if($_SESSION['reporttype'] == "Item Location"){
			  	if(isset($_SESSION['itemtype'])){
					$wherestr = "AND e.type = '".$_SESSION['itemtype']."'";
				}			
			  	$query = "SELECT i.type AS issuetype, i.serialno, i.guardresponsible, i.status, i.assignment, i.date, i.inventoryofficer, a.client, a.region, e.name FROM itemissue i, assignments a, equipment e WHERE a.callsign = i.assignment AND i.serialno = e.serialno ".$wherestr;
			  }
	
//**********************************************************************************************			// If the report is for control shift incidents
//**********************************************************************************************
			  if($_SESSION['reporttype'] == "Control Shift"){
			  	if($formvalues['timefrom'] != ""){
					$wherestr .= " AND timereported >= '".$formvalues['timefrom']."'";
			  	}
				if($formvalues['timeto'] != ""){
					$wherestr .= " AND timereported <= '".$formvalues['timeto']."'";
			  	}
			  	$query = "SELECT * FROM incidents WHERE date = '".$_SESSION['shiftdate']."' ".$wherestr;
			  }
			  if(howManyRows($query) == 0){
			  	echo "<tr><td>Sorry. There are no results for your report.</td></tr>";
			  } else {
			  ?>
      <tr style="font-family: tahoma;
	font-size: 11px;
	font-weight:bold;
	color:#FFFFFF;
	text-decoration: none;
	background-color: #010066;
	font-weight:bold">
        <?php if(in_array("4",$formvalues['detail'])){?>
        <td>Call Sign</td>
        <?php } ?>
        <?php if(in_array("3",$formvalues['detail'])){?>
        <td>Client</td>
        <?php } ?>
        <?php if(in_array("1",$formvalues['detail']) || in_array("2",$formvalues['detail'])){?>
        <td>Assigned Guards</td>
        <?php } ?>
		<?php if(in_array("5",$formvalues['detail'])){?>
        <td>Client Phone</td>
        <?php } ?>
		<?php if(in_array("6",$formvalues['detail'])){?>
        <td>Other Client Contacts</td>
        <?php } ?>
		<?php if(in_array("7",$formvalues['detail'])){?>
        <td>Duration</td>
        <?php } ?>
		<?php if(in_array("8",$formvalues['detail'])){?>
        <td>Service Type</td>
        <?php } ?>
		<?php if(in_array("21",$formvalues['detail'])){?>
        <td>Reference No</td>
        <?php } ?>
        <?php if(in_array("23",$formvalues['detail'])){?>
        <td>Assignment</td>
        <?php } ?>
		<?php if(in_array("22",$formvalues['detail'])){?>
        <td>Details</td>
        <?php } ?>
		<?php if(in_array("28",$formvalues['detail'])){?>
        <td>Checked By</td>
        <?php } ?>
		<?php if(in_array("26",$formvalues['detail'])){?>
        <td>Action(s) Taken</td>
        <?php } ?>
		<?php if(in_array("27",$formvalues['detail'])){?>
        <td>Guard Responsible</td>
        <?php } ?>
		<?php if(in_array("25",$formvalues['detail'])){?>
        <td>Date</td>
        <?php } ?>
		<?php if(in_array("24",$formvalues['detail'])){?>
        <td>Reported By</td>
        <?php } ?>
		<?php if(in_array("16",$formvalues['detail'])){?>
	  <td>Current Location</td>
	  <?php } ?>
	  <?php if(in_array("18",$formvalues['detail'])){?>
	  <td>Return Date</td>
	  <?php } ?>
	  <?php if(in_array("15",$formvalues['detail'])){?>
	  <td>In Custody Of</td>
	  <?php } ?>
	  <?php if(in_array("20",$formvalues['detail'])){?>
	  <td>Issued By</td>
	  <?php } ?>
	  <?php if(in_array("13",$formvalues['detail'])){?>
	  <td>Item Name</td>
	  <?php } ?>
	  <?php if(in_array("14",$formvalues['detail'])){?>
	  <td>Item Serial No.</td>
	  <?php } ?>
	  <?php if(in_array("19",$formvalues['detail'])){?>
	  <td>Item Status</td>
	  <?php } ?>
	  <?php if(in_array("17",$formvalues['detail'])){?>
	  <td>On Assignment</td>
	  <?php } ?>
      </tr>
      <?php 
				$i = 0;
				$result1 = mysql_query($query);
				while($line=mysql_fetch_array($result1,MYSQL_ASSOC)){
					if(($i%2)==0) {
				     	$rowclass = "background-color:#FFFFFF";
				 	} else {
				     	$rowclass = "background-color:#CCCCCC; padding-bottom:2px";
				 	}
				?>
      <tr style="<?php echo $rowclass; ?>">
        <?php if(in_array("4",$formvalues['detail'])){?>
        <td valign="top"><?php echo $line['callsign'];?></td>
        <?php } ?>
        <?php if(in_array("3",$formvalues['detail'])){?>
        <td valign="top"><?php echo $line['name'];?></td>
        <?php } ?>
        <?php if(in_array("1",$formvalues['detail']) || in_array("2",$formvalues['detail'])){?>
        <td valign="top"><?php 
		$guardarray = split(",",$line['assignedguard']);
		for($j=0;$j<count($guardarray);$j++){
			if(in_array("2",$formvalues['detail'])){ echo $guardarray[$j];}
			if(in_array("1",$formvalues['detail'])){ 
				$guard = getRowAsArray("SELECT p.firstname, p.lastname, p.othernames FROM guards g, persons p WHERE g.guardid = '".$guardarray[$j]."' AND g.personid = p.id");
				echo " (".$guard['firstname']." ".$guard['lastname']." ".$guard['othernames'].")";
			}
			echo "<br>";
		}
		?></td>
		<?php } ?>
		
		<?php if(in_array("5",$formvalues['detail'])){?>
        <td valign="top"><?php echo $line['contphone'];?></td>
        <?php } ?>
		<?php if(in_array("6",$formvalues['detail'])){?>
        <td valign="top"><?php echo "General Phone: ".$line['genphone'];
		echo "<br>Plot No.: ".$line['plotno'];
		echo "Floor No.: ".$line['floorno'];
		echo "<br>P.O.Box: ".$line['boxno'];
		echo "<br>Email: ".$line['email'];
		?></td>
        <?php } ?>
		<?php if(in_array("7",$formvalues['detail'])){?>
        <td valign="top"><?php echo $line['startdate']." TO ".$line['enddate'];?></td>
        <?php } ?>
		<?php if(in_array("8",$formvalues['detail'])){?>
        <td valign="top"><?php echo $line['servicetype'];?></td>
        <?php } ?>
		<?php if(in_array("21",$formvalues['detail'])){?>
        <td valign="top"><?php echo $line['refno'];?></td>
        <?php } ?>
        <?php if(in_array("23",$formvalues['detail'])){?>
        <td valign="top"><?php 
		$data = getRowAsArray("SELECT client FROM assignments WHERE callsign = '".$line['assignment']."'");
		echo $line['assignment']." (".$data['client'].")";?></td>
        <?php } ?>
        <?php if(in_array("22",$formvalues['detail'])){?>
        <td valign="top"><div style="width:150px"><?php echo $line['details'];?></div></td>
        <?php } ?>
		<?php if(in_array("28",$formvalues['detail'])){?>
        <td valign="top"><?php 
		$guard = getRowAsArray("SELECT p.firstname, p.lastname, p.othernames FROM guards g, persons p WHERE g.guardid = '".$line['checkedby']."' AND g.personid = p.id");
				
		echo $line['checkedby'];
		if($guard['firstname'] != "" || $guard['lastname'] != "" || $guard['othernames'] != ""){
			echo " (".$guard['firstname']." ".$guard['lastname']." ".$guard['othernames'].")";
		}?></td>
        <?php } ?>
		<?php if(in_array("26",$formvalues['detail'])){?>
        <td valign="top"><?php $actions = split(",",$line['actiontaken']);
		if(trim($line['actiontaken']) != ""){
			echo "<table>";
			for($k=0;$k<count($actions);$k++){
				$action_row = getRowAsArray("SELECT * FROM incidentactions WHERE id = '".$actions[$k]."'");
				echo "<tr><td valign=\"top\">".($k+1).".</td><td><div style=\"width:150px\">".$action_row['details']."</div></td></tr>";
				echo "<tr><td colspan=\"2\"><hr></td></tr>";
			}
			echo "</table>";
		} else { echo "None";}
		?></td>
        <?php } ?>
		<?php if(in_array("27",$formvalues['detail'])){?>
        <td valign="top"><?php 
		$guard = getRowAsArray("SELECT p.firstname, p.lastname, p.othernames FROM guards g, persons p WHERE g.guardid = '".$line['guardresponsible']."' AND g.personid = p.id");
		
		echo $line['guardresponsible'];
		if($guard['firstname'] != "" || $guard['lastname'] != "" || $guard['othernames'] != ""){
			echo " (".$guard['firstname']." ".$guard['lastname']." ".$guard['othernames'].")";
		}?></td>
        <?php } ?>
		<?php if(in_array("25",$formvalues['detail'])){?>
        <td valign="top"><?php echo date("d-M-Y",strtotime($line['date']));?></td>
        <?php } ?>
		<?php if(in_array("24",$formvalues['detail'])){?>
        <td valign="top"><?php 
		$guard = getRowAsArray("SELECT p.firstname, p.lastname, p.othernames FROM guards g, persons p WHERE g.guardid = '".$line['reportedby']."' AND g.personid = p.id");
		
		echo $line['reportedby'];
		if($guard['firstname'] != "" || $guard['lastname'] != "" || $guard['othernames'] != ""){
			echo " (".$guard['firstname']." ".$guard['lastname']." ".$guard['othernames'].")";
		}
		?></td>
        <?php } ?>
		<?php if(in_array("16",$formvalues['detail'])){?>
                          <td valign="top"><?php 
		if($line['issuetype'] == "return" && (date("d-m-Y",strtotime("now")) > date("d-m-Y",strtotime($line['date'])))){
			echo "In Store";
		} else {
			echo $line['client'];
			if(trim($line['region']) != ""){
		 		echo " (Region ".$line['region'].")";
			}
		}
		?></td>
		  <?php } ?>
		  <?php if(in_array("18",$formvalues['detail'])){?>
		  <td valign="top"><?php echo date("d-M-Y",strtotime($line['date']));?></td>
		  <?php } ?>
		  <?php if(in_array("15",$formvalues['detail'])){?>
		  <td valign="top"><?php 
$guard = getRowAsArray("SELECT p.firstname, p.lastname, p.othernames FROM guards g, persons p WHERE g.guardid = '".$line['guardresponsible']."' AND g.personid = p.id");
echo $guard['firstname']." ".$guard['lastname']." ".$guard['othernames']." (".$line['guardresponsible'].")";?></td>
		  <?php } ?>
		  <?php if(in_array("20",$formvalues['detail'])){?>
		  <td valign="top"><?php 
$person = getRowAsArray("SELECT firstname, lastname, othernames FROM persons WHERE id = '".$line['inventoryofficer']."'");
echo $person['firstname']." ".$person['lastname']." ".$person['othernames'];
?></td>
		  <?php } ?>
		  <?php if(in_array("13",$formvalues['detail'])){?>
		  <td valign="top"><?php echo $line['name'];?></td>
		  <?php } ?>
		  <?php if(in_array("14",$formvalues['detail'])){?>
		  <td valign="top"><?php echo $line['serialno'];?></td>
		  <?php } ?>
		  <?php if(in_array("19",$formvalues['detail'])){?>
		  <td valign="top"><?php echo $line['status'];?></td>
		  <?php } ?>
		  <?php if(in_array("17",$formvalues['detail'])){?>
		  <td valign="top"><?php echo $line['assignment'];?></td>
		  <?php } ?>
      </tr>
      <?php $i++; } ?>
    </table></td>
  </tr>
  <?php } ?>
</table>
<?php
} else {
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Untitled Document</title>
<script language="javascript">
function loadListFromParentWindow() {
	// load the results of the 
	document.getElementById("printresults_div").innerHTML = opener.document.getElementById("printresults_div").innerHTML;
	// change the title of this page to be the same as the opener
	document.title = <?php if(isset($_GET['title']) && trim($_GET['title']) != ""){ 
		echo "'".$_GET['title']."';";
	} else { 
		echo "opener.document.title;";
	}?>
}
</script>

<style type="text/css">
<!--
td {font-family: verdana;
	font-size: 11px;
	text-decoration: none;}
-->
</style>
</head>
<body onLoad="loadListFromParentWindow()">
<form name="contentform" id="contentform" method="post" action="popwindow.php">
  <input name="print" type="button" value="Print" onClick="window.print()">
&nbsp;&nbsp;&nbsp;
<input name="close" type="button" value="Close Window" onClick="window.close()">
<br>
<br>
<div id="printresults_div"></div>
</form>
</body>
</html>
<?php } ?>